name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      # ആൻഡ്രോയിഡ് ബിൽഡ് ഫയലുകൾ തനിയെ ശരിയാക്കുന്ന സ്റ്റെപ്പ്
      - name: Recreate Android Project Configuration
        run: |
          flutter create . --platforms=android --force
          flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-webcam-app
          path: build/app/outputs/flutter-apk/app-release.apk
