name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # lib ഫോൾഡർ മാറ്റാതെ തന്നെ Android സ്ട്രക്ചർ മാത്രം നിർമ്മിക്കുന്നു
      - name: Reconstruct Android Project Safely
        run: |
          mkdir -p lib_temp
          cp -r lib/* lib_temp/
          flutter create . --project-name=mobile_webcam_app --platforms=android --org=com.example --overwrite
          cp -r lib_temp/* lib/
          rm -rf lib_temp

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-Stream-Cam-APK
          path: build/app/outputs/flutter-apk/app-release.apk
